---

- name: Restart ambari-server
  service:
    name: ambari-server
    state: restarted
    enabled: yes
  notify:
    - "Wait for Ambari Server"

- name: Wait for Ambari Server
  wait_for:
    port: 8080
    host: 0.0.0.0
    delay: 60
